repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.(tex|sty|cls|aux|log|out|pdf|md)$'
    -   id: end-of-file-fixer
        exclude: '\.(tex|sty|cls|aux|log|out|pdf|md)$'
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5000']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
    # Run the linter.
    -   id: ruff
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
