[tox]
# 指定要測試的 Python 版本，以及預設執行的環境 (linting, typing, testing)
envlist = py310, flake8, mypy
isolated_build = True

[testenv]
# 主要測試環境，執行 pytest
description = Run Pytest unit tests
deps =
    pytest
commands =
    pytest {posargs:tests}

[testenv:flake8]
# 風格檢查環境
description = Run Flake8 for styling and linting
deps = flake8
commands = flake8 src tests main.py

[testenv:mypy]
# 靜態型別檢查環境
description = Run Mypy for static type checking
deps =
    mypy
    pandas-stubs
    pydantic
commands = mypy src main.py
